"""
Abstract interfaces and base classes for the LangChain application.

For Android Developers:
- Think of these as Kotlin Interfaces or Abstract Classes.
- Protocols (ITokenCounter, etc.) are like Kotlin interfaces that use structural typing (similar to 'interface' but more flexible).
- ABC (ILanguageModel) is exactly like a Kotlin 'abstract class'.
- @dataclass (ModelConfig) is exactly like a Kotlin 'data class'.
- Any is like Kotlin's 'Any?'.
- Optional[T] is like Kotlin's 'T?'.
"""

from abc import ABC, abstractmethod
from typing import Optional, Dict, Any, Protocol
from dataclasses import dataclass
from enum import Enum


class GenerationStrategy(Enum):
    """
    Strategies for text generation.
    Analogous to a Kotlin 'enum class'.
    """
    STANDARD = "standard"
    STREAMING = "streaming"


@dataclass
class ModelConfig:
    """
    Configuration for language models.
    
    Android Analogy: Kotlin 'data class'. It automatically generates 
    equals(), hashCode(), and toString().
    
    Attributes:
        model_name: The identifier of the model (e.g., 'gpt-4').
        temperature: Controls randomness (0.0 to 1.0).
        max_tokens: Limit on generated output length.
        api_key: Secret key for the provider.
        system_message: Initial context/instructions for the AI.
        generation_strategy: How to receive the output (standard or stream).
        additional_params: Map of extra configurations.
    """
    model_name: str
    temperature: float = 0.2
    max_tokens: int = 512
    api_key: Optional[str] = None
    system_message: Optional[str] = None
    generation_strategy: GenerationStrategy = GenerationStrategy.STANDARD
    additional_params: Optional[Dict[str, Any]] = None


@dataclass
class GenerationResult:
    """
    Result of a text generation operation.
    
    Android Analogy: A Response DTO (Data Transfer Object).
    
    Attributes:
        content: The actual text generated by the AI.
        tokens_used: Cost-related metric.
        cost: Estimated USD cost of the call.
        metadata: Extra info from the provider.
        strategy_used: Which strategy was used for this result.
    """
    content: str
    tokens_used: Optional[int] = None
    cost: Optional[float] = None
    metadata: Optional[Dict[str, Any]] = None
    strategy_used: Optional[GenerationStrategy] = None


# Segregated Token Management Interfaces
class ITokenCounter(Protocol):
    """
    Interface for token counting operations.
    
    Python Protocol Note: This is a "Structural Type". Any class that implements 
    a 'count_tokens' method with this signature is considered an ITokenCounter, 
    even if it doesn't explicitly inherit from it. 
    Similar to Go interfaces or Kotlin's duck typing if it had it.
    """
    
    def count_tokens(self, text: str, model_name: str) -> int:
        """
        Count tokens in text for a specific model.
        
        Args:
            text: Input string.
            model_name: Model identifier for specific encoding.
            
        Returns:
            Number of tokens.
        """
        ...


class ICostEstimator(Protocol):
    """Interface for cost estimation operations."""
    
    def estimate_cost(self, tokens: int, model_name: str, is_output: bool = False) -> float:
        """Estimate cost for token usage based on pricing data."""
        ...


class IUsageTracker(Protocol):
    """Interface for usage tracking and persistence."""
    
    def log_usage(self, model_name: str, tokens: int, operation_type: str, is_output: bool = False) -> None:
        """Log token usage to persistent storage (like SharedPreferences/Room)."""
        ...
    
    def get_usage_summary(self) -> Dict[str, Any]:
        """Get aggregate usage data."""
        ...


class ITokenManager(ITokenCounter, ICostEstimator, IUsageTracker, Protocol):
    """
    Combined interface for token management.
    Analogous to Interface Inheritance in Kotlin.
    """
    pass


# Segregated User Interaction Interfaces
class IUserPrompt(Protocol):
    """Interface for user input/prompting."""
    
    def prompt_continue(self) -> bool:
        """Prompt user to continue. Returns True if user says 'yes'."""
        ...
    
    def prompt_choice(self, message: str, choices: list[str]) -> str:
        """Show a list of choices and return the selected one."""
        ...


class IUserDisplay(Protocol):
    """Interface for UI output operations (Console in this case)."""
    
    def display_info(self, message: str) -> None:
        """Log/Show informational message."""
        ...
    
    def display_error(self, error: str) -> None:
        """Log/Show error message."""
        ...
    
    def display_warning(self, message: str) -> None:
        """Log/Show warning message."""
        ...


class IUserInteraction(IUserPrompt, IUserDisplay, Protocol):
    """Facade interface for UI interactions."""
    pass


# Model-related Interfaces
class IModelValidator(Protocol):
    """Interface for model configuration validation."""
    
    def validate_config(self, config: ModelConfig) -> None:
        """Validate if a ModelConfig is valid for a specific provider."""
        ...


class IApiKeyValidator(Protocol):
    """Interface for API key validation."""
    
    def validate_key(self, api_key: str, provider: str) -> bool:
        """Check if an API key format or validity is correct."""
        ...


class IGenerationStrategy(Protocol):
    """Interface for generation strategy implementations."""
    
    def generate(self, model: Any, prompt: str, config: ModelConfig) -> GenerationResult:
        """Execute text generation."""
        ...
    
    def supports_model(self, provider: str) -> bool:
        """Check if provider is compatible with this strategy."""
        ...


class ILanguageModel(ABC):
    """
    Abstract base class for all LLM implementations.
    
    Android Analogy: 'abstract class ILanguageModel(val config: ModelConfig)'.
    
    Note: Python uses '__init__' for constructors.
    """
    
    def __init__(self, config: ModelConfig):
        """
        Constructor.
        
        Args:
            config: The model configuration data class.
        """
        self.config = config
        self._validate_config()
    
    @abstractmethod
    def _validate_config(self) -> None:
        """
        Validate the configuration. 
        Must be implemented by subclasses.
        """
        pass
    
    @abstractmethod
    def generate(self, prompt: str, **kwargs) -> GenerationResult:
        """
        Main generation entry point.
        
        **kwargs: Analogous to passing a Map or optional parameters in Kotlin.
        """
        pass
    
    @abstractmethod
    def get_model_info(self) -> Dict[str, Any]:
        """Return provider-specific metadata."""
        pass
    
    @property
    @abstractmethod
    def provider(self) -> str:
        """
        Read-only property for the provider name.
        Like a Kotlin 'val provider: String'.
        """
        pass


class IModelFactory(Protocol):
    """
    Factory interface for creating model instances.
    Analogous to the Factory Pattern in Android.
    """
    
    def create_model(self, provider: str, config: ModelConfig) -> ILanguageModel:
        """Create and return an ILanguageModel implementation."""
        ...
    
    def get_available_providers(self) -> list[str]:
        """List of supported AI backends."""
        ...
    
    def register_model(self, provider: str, model_class: type) -> None:
        """Register a class to a provider string (Dynamic Loading)."""
        ...


class IFileExporter(Protocol):
    """Interface for data persistence/export (JSON -> Excel)."""

    def export_to_excel(self, input_file: str, output_file: str) -> bool:
        """
        Export contents of an input file to an Excel sheet.
        
        Args:
            input_file: Source path.
            output_file: Destination path (.xlsx).
            
        Returns:
            True if successful.
        """
        ...